export 'package:mobile_app/src/pages/home_page.dart';
export 'package:mobile_app/src/pages/gallery_page.dart';
export 'package:mobile_app/src/pages/pong_page.dart';
export 'package:mobile_app/src/pages/localization_system_page.dart';
export 'package:mobile_app/src/pages/star_page.dart';
export 'package:mobile_app/src/pages/ball.dart';
export 'package:mobile_app/src/pages/brick.dart';
export 'package:mobile_app/src/pages/coverscreen.dart';
export 'package:mobile_app/src/pages/home_page.dart';
